//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.HR_Mgt_API {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StaffCreationResposeObject", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class StaffCreationResposeObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StaffIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusDescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string StaffId {
            get {
                return this.StaffIdField;
            }
            set {
                if ((object.ReferenceEquals(this.StaffIdField, value) != true)) {
                    this.StaffIdField = value;
                    this.RaisePropertyChanged("StaffId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string StatusCode {
            get {
                return this.StatusCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusCodeField, value) != true)) {
                    this.StatusCodeField = value;
                    this.RaisePropertyChanged("StatusCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string StatusDescription {
            get {
                return this.StatusDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusDescriptionField, value) != true)) {
                    this.StatusDescriptionField = value;
                    this.RaisePropertyChanged("StatusDescription");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetStaffDetailsResponseObject", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class GetStaffDetailsResponseObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplication1.HR_Mgt_API.StaffObject[] StaffListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusDescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public WebApplication1.HR_Mgt_API.StaffObject[] StaffList {
            get {
                return this.StaffListField;
            }
            set {
                if ((object.ReferenceEquals(this.StaffListField, value) != true)) {
                    this.StaffListField = value;
                    this.RaisePropertyChanged("StaffList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string StatusCode {
            get {
                return this.StatusCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusCodeField, value) != true)) {
                    this.StatusCodeField = value;
                    this.RaisePropertyChanged("StatusCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string StatusDescription {
            get {
                return this.StatusDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusDescriptionField, value) != true)) {
                    this.StatusDescriptionField = value;
                    this.RaisePropertyChanged("StatusDescription");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StaffObject", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class StaffObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StaffIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OtherNamesField;
        
        private System.DateTime DOBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDPhotoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string StaffId {
            get {
                return this.StaffIdField;
            }
            set {
                if ((object.ReferenceEquals(this.StaffIdField, value) != true)) {
                    this.StaffIdField = value;
                    this.RaisePropertyChanged("StaffId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SurName {
            get {
                return this.SurNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurNameField, value) != true)) {
                    this.SurNameField = value;
                    this.RaisePropertyChanged("SurName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string OtherNames {
            get {
                return this.OtherNamesField;
            }
            set {
                if ((object.ReferenceEquals(this.OtherNamesField, value) != true)) {
                    this.OtherNamesField = value;
                    this.RaisePropertyChanged("OtherNames");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime DOB {
            get {
                return this.DOBField;
            }
            set {
                if ((this.DOBField.Equals(value) != true)) {
                    this.DOBField = value;
                    this.RaisePropertyChanged("DOB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string IDPhoto {
            get {
                return this.IDPhotoField;
            }
            set {
                if ((object.ReferenceEquals(this.IDPhotoField, value) != true)) {
                    this.IDPhotoField = value;
                    this.RaisePropertyChanged("IDPhoto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseObject", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ResponseObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusDescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string StatusCode {
            get {
                return this.StatusCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusCodeField, value) != true)) {
                    this.StatusCodeField = value;
                    this.RaisePropertyChanged("StatusCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string StatusDescription {
            get {
                return this.StatusDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusDescriptionField, value) != true)) {
                    this.StatusDescriptionField = value;
                    this.RaisePropertyChanged("StatusDescription");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginResponseObject", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class LoginResponseObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplication1.HR_Mgt_API.SessionObject SessionDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusDescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public WebApplication1.HR_Mgt_API.SessionObject SessionDetails {
            get {
                return this.SessionDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.SessionDetailsField, value) != true)) {
                    this.SessionDetailsField = value;
                    this.RaisePropertyChanged("SessionDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string StatusCode {
            get {
                return this.StatusCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusCodeField, value) != true)) {
                    this.StatusCodeField = value;
                    this.RaisePropertyChanged("StatusCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string StatusDescription {
            get {
                return this.StatusDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusDescriptionField, value) != true)) {
                    this.StatusDescriptionField = value;
                    this.RaisePropertyChanged("StatusDescription");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SessionObject", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class SessionObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SessionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SessionNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SessionRoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SessionStatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SessionId {
            get {
                return this.SessionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SessionIdField, value) != true)) {
                    this.SessionIdField = value;
                    this.RaisePropertyChanged("SessionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SessionName {
            get {
                return this.SessionNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SessionNameField, value) != true)) {
                    this.SessionNameField = value;
                    this.RaisePropertyChanged("SessionName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SessionRole {
            get {
                return this.SessionRoleField;
            }
            set {
                if ((object.ReferenceEquals(this.SessionRoleField, value) != true)) {
                    this.SessionRoleField = value;
                    this.RaisePropertyChanged("SessionRole");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SessionStatus {
            get {
                return this.SessionStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.SessionStatusField, value) != true)) {
                    this.SessionStatusField = value;
                    this.RaisePropertyChanged("SessionStatus");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetTemporaryIdsResponseObject", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class GetTemporaryIdsResponseObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplication1.HR_Mgt_API.TemporaryIdObject[] TemporaryIdsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string StatusCode {
            get {
                return this.StatusCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusCodeField, value) != true)) {
                    this.StatusCodeField = value;
                    this.RaisePropertyChanged("StatusCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string StatusDescription {
            get {
                return this.StatusDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusDescriptionField, value) != true)) {
                    this.StatusDescriptionField = value;
                    this.RaisePropertyChanged("StatusDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public WebApplication1.HR_Mgt_API.TemporaryIdObject[] TemporaryIds {
            get {
                return this.TemporaryIdsField;
            }
            set {
                if ((object.ReferenceEquals(this.TemporaryIdsField, value) != true)) {
                    this.TemporaryIdsField = value;
                    this.RaisePropertyChanged("TemporaryIds");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TemporaryIdObject", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TemporaryIdObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TemporaryIdField;
        
        private System.DateTime CreationdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        private System.DateTime ExpirationdateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TemporaryId {
            get {
                return this.TemporaryIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TemporaryIdField, value) != true)) {
                    this.TemporaryIdField = value;
                    this.RaisePropertyChanged("TemporaryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.DateTime Creationdate {
            get {
                return this.CreationdateField;
            }
            set {
                if ((this.CreationdateField.Equals(value) != true)) {
                    this.CreationdateField = value;
                    this.RaisePropertyChanged("Creationdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime Expirationdate {
            get {
                return this.ExpirationdateField;
            }
            set {
                if ((this.ExpirationdateField.Equals(value) != true)) {
                    this.ExpirationdateField = value;
                    this.RaisePropertyChanged("Expirationdate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HR_Mgt_API.HRManagementAPISoap")]
    public interface HRManagementAPISoap {
        
        // CODEGEN: Generating message contract since element name TemporaryID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegisterNewStaff", ReplyAction="*")]
        WebApplication1.HR_Mgt_API.RegisterNewStaffResponse RegisterNewStaff(WebApplication1.HR_Mgt_API.RegisterNewStaffRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegisterNewStaff", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.HR_Mgt_API.RegisterNewStaffResponse> RegisterNewStaffAsync(WebApplication1.HR_Mgt_API.RegisterNewStaffRequest request);
        
        // CODEGEN: Generating message contract since element name StaffID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStaffDetails", ReplyAction="*")]
        WebApplication1.HR_Mgt_API.GetStaffDetailsResponse GetStaffDetails(WebApplication1.HR_Mgt_API.GetStaffDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStaffDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.HR_Mgt_API.GetStaffDetailsResponse> GetStaffDetailsAsync(WebApplication1.HR_Mgt_API.GetStaffDetailsRequest request);
        
        // CODEGEN: Generating message contract since element name StaffId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateStaffDetails", ReplyAction="*")]
        WebApplication1.HR_Mgt_API.UpdateStaffDetailsResponse UpdateStaffDetails(WebApplication1.HR_Mgt_API.UpdateStaffDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateStaffDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.HR_Mgt_API.UpdateStaffDetailsResponse> UpdateStaffDetailsAsync(WebApplication1.HR_Mgt_API.UpdateStaffDetailsRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        WebApplication1.HR_Mgt_API.LoginResponse Login(WebApplication1.HR_Mgt_API.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.HR_Mgt_API.LoginResponse> LoginAsync(WebApplication1.HR_Mgt_API.LoginRequest request);
        
        // CODEGEN: Generating message contract since element name sessionId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Logout", ReplyAction="*")]
        WebApplication1.HR_Mgt_API.LogoutResponse Logout(WebApplication1.HR_Mgt_API.LogoutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Logout", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.HR_Mgt_API.LogoutResponse> LogoutAsync(WebApplication1.HR_Mgt_API.LogoutRequest request);
        
        // CODEGEN: Generating message contract since element name sessionId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateTemporaryIDs", ReplyAction="*")]
        WebApplication1.HR_Mgt_API.CreateTemporaryIDsResponse CreateTemporaryIDs(WebApplication1.HR_Mgt_API.CreateTemporaryIDsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateTemporaryIDs", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.HR_Mgt_API.CreateTemporaryIDsResponse> CreateTemporaryIDsAsync(WebApplication1.HR_Mgt_API.CreateTemporaryIDsRequest request);
        
        // CODEGEN: Generating message contract since element name status from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewTemporaryIDs", ReplyAction="*")]
        WebApplication1.HR_Mgt_API.ViewTemporaryIDsResponse ViewTemporaryIDs(WebApplication1.HR_Mgt_API.ViewTemporaryIDsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewTemporaryIDs", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.HR_Mgt_API.ViewTemporaryIDsResponse> ViewTemporaryIDsAsync(WebApplication1.HR_Mgt_API.ViewTemporaryIDsRequest request);
        
        // CODEGEN: Generating message contract since element name GetAPIStatsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAPIStats", ReplyAction="*")]
        WebApplication1.HR_Mgt_API.GetAPIStatsResponse GetAPIStats(WebApplication1.HR_Mgt_API.GetAPIStatsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAPIStats", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.HR_Mgt_API.GetAPIStatsResponse> GetAPIStatsAsync(WebApplication1.HR_Mgt_API.GetAPIStatsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterNewStaffRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterNewStaff", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.HR_Mgt_API.RegisterNewStaffRequestBody Body;
        
        public RegisterNewStaffRequest() {
        }
        
        public RegisterNewStaffRequest(WebApplication1.HR_Mgt_API.RegisterNewStaffRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterNewStaffRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TemporaryID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Surname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Othernames;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime DOB;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string IDPhoto;
        
        public RegisterNewStaffRequestBody() {
        }
        
        public RegisterNewStaffRequestBody(string TemporaryID, string Surname, string Othernames, System.DateTime DOB, string IDPhoto) {
            this.TemporaryID = TemporaryID;
            this.Surname = Surname;
            this.Othernames = Othernames;
            this.DOB = DOB;
            this.IDPhoto = IDPhoto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterNewStaffResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterNewStaffResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.HR_Mgt_API.RegisterNewStaffResponseBody Body;
        
        public RegisterNewStaffResponse() {
        }
        
        public RegisterNewStaffResponse(WebApplication1.HR_Mgt_API.RegisterNewStaffResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterNewStaffResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebApplication1.HR_Mgt_API.StaffCreationResposeObject RegisterNewStaffResult;
        
        public RegisterNewStaffResponseBody() {
        }
        
        public RegisterNewStaffResponseBody(WebApplication1.HR_Mgt_API.StaffCreationResposeObject RegisterNewStaffResult) {
            this.RegisterNewStaffResult = RegisterNewStaffResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStaffDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStaffDetails", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.HR_Mgt_API.GetStaffDetailsRequestBody Body;
        
        public GetStaffDetailsRequest() {
        }
        
        public GetStaffDetailsRequest(WebApplication1.HR_Mgt_API.GetStaffDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStaffDetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string StaffID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sessionId;
        
        public GetStaffDetailsRequestBody() {
        }
        
        public GetStaffDetailsRequestBody(string StaffID, string sessionId) {
            this.StaffID = StaffID;
            this.sessionId = sessionId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStaffDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStaffDetailsResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.HR_Mgt_API.GetStaffDetailsResponseBody Body;
        
        public GetStaffDetailsResponse() {
        }
        
        public GetStaffDetailsResponse(WebApplication1.HR_Mgt_API.GetStaffDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStaffDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebApplication1.HR_Mgt_API.GetStaffDetailsResponseObject GetStaffDetailsResult;
        
        public GetStaffDetailsResponseBody() {
        }
        
        public GetStaffDetailsResponseBody(WebApplication1.HR_Mgt_API.GetStaffDetailsResponseObject GetStaffDetailsResult) {
            this.GetStaffDetailsResult = GetStaffDetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateStaffDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateStaffDetails", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.HR_Mgt_API.UpdateStaffDetailsRequestBody Body;
        
        public UpdateStaffDetailsRequest() {
        }
        
        public UpdateStaffDetailsRequest(WebApplication1.HR_Mgt_API.UpdateStaffDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateStaffDetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string StaffId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime NewDOB;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string NewIDPhoto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string sessionId;
        
        public UpdateStaffDetailsRequestBody() {
        }
        
        public UpdateStaffDetailsRequestBody(string StaffId, System.DateTime NewDOB, string NewIDPhoto, string username, string sessionId) {
            this.StaffId = StaffId;
            this.NewDOB = NewDOB;
            this.NewIDPhoto = NewIDPhoto;
            this.username = username;
            this.sessionId = sessionId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateStaffDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateStaffDetailsResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.HR_Mgt_API.UpdateStaffDetailsResponseBody Body;
        
        public UpdateStaffDetailsResponse() {
        }
        
        public UpdateStaffDetailsResponse(WebApplication1.HR_Mgt_API.UpdateStaffDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateStaffDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebApplication1.HR_Mgt_API.ResponseObject UpdateStaffDetailsResult;
        
        public UpdateStaffDetailsResponseBody() {
        }
        
        public UpdateStaffDetailsResponseBody(WebApplication1.HR_Mgt_API.ResponseObject UpdateStaffDetailsResult) {
            this.UpdateStaffDetailsResult = UpdateStaffDetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.HR_Mgt_API.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(WebApplication1.HR_Mgt_API.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.HR_Mgt_API.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(WebApplication1.HR_Mgt_API.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebApplication1.HR_Mgt_API.LoginResponseObject LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(WebApplication1.HR_Mgt_API.LoginResponseObject LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogoutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Logout", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.HR_Mgt_API.LogoutRequestBody Body;
        
        public LogoutRequest() {
        }
        
        public LogoutRequest(WebApplication1.HR_Mgt_API.LogoutRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LogoutRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionId;
        
        public LogoutRequestBody() {
        }
        
        public LogoutRequestBody(string sessionId) {
            this.sessionId = sessionId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogoutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogoutResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.HR_Mgt_API.LogoutResponseBody Body;
        
        public LogoutResponse() {
        }
        
        public LogoutResponse(WebApplication1.HR_Mgt_API.LogoutResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LogoutResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebApplication1.HR_Mgt_API.ResponseObject LogoutResult;
        
        public LogoutResponseBody() {
        }
        
        public LogoutResponseBody(WebApplication1.HR_Mgt_API.ResponseObject LogoutResult) {
            this.LogoutResult = LogoutResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateTemporaryIDsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateTemporaryIDs", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.HR_Mgt_API.CreateTemporaryIDsRequestBody Body;
        
        public CreateTemporaryIDsRequest() {
        }
        
        public CreateTemporaryIDsRequest(WebApplication1.HR_Mgt_API.CreateTemporaryIDsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateTemporaryIDsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int count;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int durationinseconds;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sessionId;
        
        public CreateTemporaryIDsRequestBody() {
        }
        
        public CreateTemporaryIDsRequestBody(int count, int durationinseconds, string sessionId) {
            this.count = count;
            this.durationinseconds = durationinseconds;
            this.sessionId = sessionId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateTemporaryIDsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateTemporaryIDsResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.HR_Mgt_API.CreateTemporaryIDsResponseBody Body;
        
        public CreateTemporaryIDsResponse() {
        }
        
        public CreateTemporaryIDsResponse(WebApplication1.HR_Mgt_API.CreateTemporaryIDsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateTemporaryIDsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebApplication1.HR_Mgt_API.GetTemporaryIdsResponseObject CreateTemporaryIDsResult;
        
        public CreateTemporaryIDsResponseBody() {
        }
        
        public CreateTemporaryIDsResponseBody(WebApplication1.HR_Mgt_API.GetTemporaryIdsResponseObject CreateTemporaryIDsResult) {
            this.CreateTemporaryIDsResult = CreateTemporaryIDsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ViewTemporaryIDsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ViewTemporaryIDs", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.HR_Mgt_API.ViewTemporaryIDsRequestBody Body;
        
        public ViewTemporaryIDsRequest() {
        }
        
        public ViewTemporaryIDsRequest(WebApplication1.HR_Mgt_API.ViewTemporaryIDsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ViewTemporaryIDsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string status;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sessionId;
        
        public ViewTemporaryIDsRequestBody() {
        }
        
        public ViewTemporaryIDsRequestBody(string status, string sessionId) {
            this.status = status;
            this.sessionId = sessionId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ViewTemporaryIDsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ViewTemporaryIDsResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.HR_Mgt_API.ViewTemporaryIDsResponseBody Body;
        
        public ViewTemporaryIDsResponse() {
        }
        
        public ViewTemporaryIDsResponse(WebApplication1.HR_Mgt_API.ViewTemporaryIDsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ViewTemporaryIDsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebApplication1.HR_Mgt_API.GetTemporaryIdsResponseObject ViewTemporaryIDsResult;
        
        public ViewTemporaryIDsResponseBody() {
        }
        
        public ViewTemporaryIDsResponseBody(WebApplication1.HR_Mgt_API.GetTemporaryIdsResponseObject ViewTemporaryIDsResult) {
            this.ViewTemporaryIDsResult = ViewTemporaryIDsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAPIStatsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAPIStats", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.HR_Mgt_API.GetAPIStatsRequestBody Body;
        
        public GetAPIStatsRequest() {
        }
        
        public GetAPIStatsRequest(WebApplication1.HR_Mgt_API.GetAPIStatsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAPIStatsRequestBody {
        
        public GetAPIStatsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAPIStatsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAPIStatsResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.HR_Mgt_API.GetAPIStatsResponseBody Body;
        
        public GetAPIStatsResponse() {
        }
        
        public GetAPIStatsResponse(WebApplication1.HR_Mgt_API.GetAPIStatsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAPIStatsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAPIStatsResult;
        
        public GetAPIStatsResponseBody() {
        }
        
        public GetAPIStatsResponseBody(string GetAPIStatsResult) {
            this.GetAPIStatsResult = GetAPIStatsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HRManagementAPISoapChannel : WebApplication1.HR_Mgt_API.HRManagementAPISoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HRManagementAPISoapClient : System.ServiceModel.ClientBase<WebApplication1.HR_Mgt_API.HRManagementAPISoap>, WebApplication1.HR_Mgt_API.HRManagementAPISoap {
        
        public HRManagementAPISoapClient() {
        }
        
        public HRManagementAPISoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HRManagementAPISoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HRManagementAPISoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HRManagementAPISoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.HR_Mgt_API.RegisterNewStaffResponse WebApplication1.HR_Mgt_API.HRManagementAPISoap.RegisterNewStaff(WebApplication1.HR_Mgt_API.RegisterNewStaffRequest request) {
            return base.Channel.RegisterNewStaff(request);
        }
        
        public WebApplication1.HR_Mgt_API.StaffCreationResposeObject RegisterNewStaff(string TemporaryID, string Surname, string Othernames, System.DateTime DOB, string IDPhoto) {
            WebApplication1.HR_Mgt_API.RegisterNewStaffRequest inValue = new WebApplication1.HR_Mgt_API.RegisterNewStaffRequest();
            inValue.Body = new WebApplication1.HR_Mgt_API.RegisterNewStaffRequestBody();
            inValue.Body.TemporaryID = TemporaryID;
            inValue.Body.Surname = Surname;
            inValue.Body.Othernames = Othernames;
            inValue.Body.DOB = DOB;
            inValue.Body.IDPhoto = IDPhoto;
            WebApplication1.HR_Mgt_API.RegisterNewStaffResponse retVal = ((WebApplication1.HR_Mgt_API.HRManagementAPISoap)(this)).RegisterNewStaff(inValue);
            return retVal.Body.RegisterNewStaffResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.HR_Mgt_API.RegisterNewStaffResponse> WebApplication1.HR_Mgt_API.HRManagementAPISoap.RegisterNewStaffAsync(WebApplication1.HR_Mgt_API.RegisterNewStaffRequest request) {
            return base.Channel.RegisterNewStaffAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.HR_Mgt_API.RegisterNewStaffResponse> RegisterNewStaffAsync(string TemporaryID, string Surname, string Othernames, System.DateTime DOB, string IDPhoto) {
            WebApplication1.HR_Mgt_API.RegisterNewStaffRequest inValue = new WebApplication1.HR_Mgt_API.RegisterNewStaffRequest();
            inValue.Body = new WebApplication1.HR_Mgt_API.RegisterNewStaffRequestBody();
            inValue.Body.TemporaryID = TemporaryID;
            inValue.Body.Surname = Surname;
            inValue.Body.Othernames = Othernames;
            inValue.Body.DOB = DOB;
            inValue.Body.IDPhoto = IDPhoto;
            return ((WebApplication1.HR_Mgt_API.HRManagementAPISoap)(this)).RegisterNewStaffAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.HR_Mgt_API.GetStaffDetailsResponse WebApplication1.HR_Mgt_API.HRManagementAPISoap.GetStaffDetails(WebApplication1.HR_Mgt_API.GetStaffDetailsRequest request) {
            return base.Channel.GetStaffDetails(request);
        }
        
        public WebApplication1.HR_Mgt_API.GetStaffDetailsResponseObject GetStaffDetails(string StaffID, string sessionId) {
            WebApplication1.HR_Mgt_API.GetStaffDetailsRequest inValue = new WebApplication1.HR_Mgt_API.GetStaffDetailsRequest();
            inValue.Body = new WebApplication1.HR_Mgt_API.GetStaffDetailsRequestBody();
            inValue.Body.StaffID = StaffID;
            inValue.Body.sessionId = sessionId;
            WebApplication1.HR_Mgt_API.GetStaffDetailsResponse retVal = ((WebApplication1.HR_Mgt_API.HRManagementAPISoap)(this)).GetStaffDetails(inValue);
            return retVal.Body.GetStaffDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.HR_Mgt_API.GetStaffDetailsResponse> WebApplication1.HR_Mgt_API.HRManagementAPISoap.GetStaffDetailsAsync(WebApplication1.HR_Mgt_API.GetStaffDetailsRequest request) {
            return base.Channel.GetStaffDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.HR_Mgt_API.GetStaffDetailsResponse> GetStaffDetailsAsync(string StaffID, string sessionId) {
            WebApplication1.HR_Mgt_API.GetStaffDetailsRequest inValue = new WebApplication1.HR_Mgt_API.GetStaffDetailsRequest();
            inValue.Body = new WebApplication1.HR_Mgt_API.GetStaffDetailsRequestBody();
            inValue.Body.StaffID = StaffID;
            inValue.Body.sessionId = sessionId;
            return ((WebApplication1.HR_Mgt_API.HRManagementAPISoap)(this)).GetStaffDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.HR_Mgt_API.UpdateStaffDetailsResponse WebApplication1.HR_Mgt_API.HRManagementAPISoap.UpdateStaffDetails(WebApplication1.HR_Mgt_API.UpdateStaffDetailsRequest request) {
            return base.Channel.UpdateStaffDetails(request);
        }
        
        public WebApplication1.HR_Mgt_API.ResponseObject UpdateStaffDetails(string StaffId, System.DateTime NewDOB, string NewIDPhoto, string username, string sessionId) {
            WebApplication1.HR_Mgt_API.UpdateStaffDetailsRequest inValue = new WebApplication1.HR_Mgt_API.UpdateStaffDetailsRequest();
            inValue.Body = new WebApplication1.HR_Mgt_API.UpdateStaffDetailsRequestBody();
            inValue.Body.StaffId = StaffId;
            inValue.Body.NewDOB = NewDOB;
            inValue.Body.NewIDPhoto = NewIDPhoto;
            inValue.Body.username = username;
            inValue.Body.sessionId = sessionId;
            WebApplication1.HR_Mgt_API.UpdateStaffDetailsResponse retVal = ((WebApplication1.HR_Mgt_API.HRManagementAPISoap)(this)).UpdateStaffDetails(inValue);
            return retVal.Body.UpdateStaffDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.HR_Mgt_API.UpdateStaffDetailsResponse> WebApplication1.HR_Mgt_API.HRManagementAPISoap.UpdateStaffDetailsAsync(WebApplication1.HR_Mgt_API.UpdateStaffDetailsRequest request) {
            return base.Channel.UpdateStaffDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.HR_Mgt_API.UpdateStaffDetailsResponse> UpdateStaffDetailsAsync(string StaffId, System.DateTime NewDOB, string NewIDPhoto, string username, string sessionId) {
            WebApplication1.HR_Mgt_API.UpdateStaffDetailsRequest inValue = new WebApplication1.HR_Mgt_API.UpdateStaffDetailsRequest();
            inValue.Body = new WebApplication1.HR_Mgt_API.UpdateStaffDetailsRequestBody();
            inValue.Body.StaffId = StaffId;
            inValue.Body.NewDOB = NewDOB;
            inValue.Body.NewIDPhoto = NewIDPhoto;
            inValue.Body.username = username;
            inValue.Body.sessionId = sessionId;
            return ((WebApplication1.HR_Mgt_API.HRManagementAPISoap)(this)).UpdateStaffDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.HR_Mgt_API.LoginResponse WebApplication1.HR_Mgt_API.HRManagementAPISoap.Login(WebApplication1.HR_Mgt_API.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public WebApplication1.HR_Mgt_API.LoginResponseObject Login(string username, string password) {
            WebApplication1.HR_Mgt_API.LoginRequest inValue = new WebApplication1.HR_Mgt_API.LoginRequest();
            inValue.Body = new WebApplication1.HR_Mgt_API.LoginRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            WebApplication1.HR_Mgt_API.LoginResponse retVal = ((WebApplication1.HR_Mgt_API.HRManagementAPISoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.HR_Mgt_API.LoginResponse> WebApplication1.HR_Mgt_API.HRManagementAPISoap.LoginAsync(WebApplication1.HR_Mgt_API.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.HR_Mgt_API.LoginResponse> LoginAsync(string username, string password) {
            WebApplication1.HR_Mgt_API.LoginRequest inValue = new WebApplication1.HR_Mgt_API.LoginRequest();
            inValue.Body = new WebApplication1.HR_Mgt_API.LoginRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((WebApplication1.HR_Mgt_API.HRManagementAPISoap)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.HR_Mgt_API.LogoutResponse WebApplication1.HR_Mgt_API.HRManagementAPISoap.Logout(WebApplication1.HR_Mgt_API.LogoutRequest request) {
            return base.Channel.Logout(request);
        }
        
        public WebApplication1.HR_Mgt_API.ResponseObject Logout(string sessionId) {
            WebApplication1.HR_Mgt_API.LogoutRequest inValue = new WebApplication1.HR_Mgt_API.LogoutRequest();
            inValue.Body = new WebApplication1.HR_Mgt_API.LogoutRequestBody();
            inValue.Body.sessionId = sessionId;
            WebApplication1.HR_Mgt_API.LogoutResponse retVal = ((WebApplication1.HR_Mgt_API.HRManagementAPISoap)(this)).Logout(inValue);
            return retVal.Body.LogoutResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.HR_Mgt_API.LogoutResponse> WebApplication1.HR_Mgt_API.HRManagementAPISoap.LogoutAsync(WebApplication1.HR_Mgt_API.LogoutRequest request) {
            return base.Channel.LogoutAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.HR_Mgt_API.LogoutResponse> LogoutAsync(string sessionId) {
            WebApplication1.HR_Mgt_API.LogoutRequest inValue = new WebApplication1.HR_Mgt_API.LogoutRequest();
            inValue.Body = new WebApplication1.HR_Mgt_API.LogoutRequestBody();
            inValue.Body.sessionId = sessionId;
            return ((WebApplication1.HR_Mgt_API.HRManagementAPISoap)(this)).LogoutAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.HR_Mgt_API.CreateTemporaryIDsResponse WebApplication1.HR_Mgt_API.HRManagementAPISoap.CreateTemporaryIDs(WebApplication1.HR_Mgt_API.CreateTemporaryIDsRequest request) {
            return base.Channel.CreateTemporaryIDs(request);
        }
        
        public WebApplication1.HR_Mgt_API.GetTemporaryIdsResponseObject CreateTemporaryIDs(int count, int durationinseconds, string sessionId) {
            WebApplication1.HR_Mgt_API.CreateTemporaryIDsRequest inValue = new WebApplication1.HR_Mgt_API.CreateTemporaryIDsRequest();
            inValue.Body = new WebApplication1.HR_Mgt_API.CreateTemporaryIDsRequestBody();
            inValue.Body.count = count;
            inValue.Body.durationinseconds = durationinseconds;
            inValue.Body.sessionId = sessionId;
            WebApplication1.HR_Mgt_API.CreateTemporaryIDsResponse retVal = ((WebApplication1.HR_Mgt_API.HRManagementAPISoap)(this)).CreateTemporaryIDs(inValue);
            return retVal.Body.CreateTemporaryIDsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.HR_Mgt_API.CreateTemporaryIDsResponse> WebApplication1.HR_Mgt_API.HRManagementAPISoap.CreateTemporaryIDsAsync(WebApplication1.HR_Mgt_API.CreateTemporaryIDsRequest request) {
            return base.Channel.CreateTemporaryIDsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.HR_Mgt_API.CreateTemporaryIDsResponse> CreateTemporaryIDsAsync(int count, int durationinseconds, string sessionId) {
            WebApplication1.HR_Mgt_API.CreateTemporaryIDsRequest inValue = new WebApplication1.HR_Mgt_API.CreateTemporaryIDsRequest();
            inValue.Body = new WebApplication1.HR_Mgt_API.CreateTemporaryIDsRequestBody();
            inValue.Body.count = count;
            inValue.Body.durationinseconds = durationinseconds;
            inValue.Body.sessionId = sessionId;
            return ((WebApplication1.HR_Mgt_API.HRManagementAPISoap)(this)).CreateTemporaryIDsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.HR_Mgt_API.ViewTemporaryIDsResponse WebApplication1.HR_Mgt_API.HRManagementAPISoap.ViewTemporaryIDs(WebApplication1.HR_Mgt_API.ViewTemporaryIDsRequest request) {
            return base.Channel.ViewTemporaryIDs(request);
        }
        
        public WebApplication1.HR_Mgt_API.GetTemporaryIdsResponseObject ViewTemporaryIDs(string status, string sessionId) {
            WebApplication1.HR_Mgt_API.ViewTemporaryIDsRequest inValue = new WebApplication1.HR_Mgt_API.ViewTemporaryIDsRequest();
            inValue.Body = new WebApplication1.HR_Mgt_API.ViewTemporaryIDsRequestBody();
            inValue.Body.status = status;
            inValue.Body.sessionId = sessionId;
            WebApplication1.HR_Mgt_API.ViewTemporaryIDsResponse retVal = ((WebApplication1.HR_Mgt_API.HRManagementAPISoap)(this)).ViewTemporaryIDs(inValue);
            return retVal.Body.ViewTemporaryIDsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.HR_Mgt_API.ViewTemporaryIDsResponse> WebApplication1.HR_Mgt_API.HRManagementAPISoap.ViewTemporaryIDsAsync(WebApplication1.HR_Mgt_API.ViewTemporaryIDsRequest request) {
            return base.Channel.ViewTemporaryIDsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.HR_Mgt_API.ViewTemporaryIDsResponse> ViewTemporaryIDsAsync(string status, string sessionId) {
            WebApplication1.HR_Mgt_API.ViewTemporaryIDsRequest inValue = new WebApplication1.HR_Mgt_API.ViewTemporaryIDsRequest();
            inValue.Body = new WebApplication1.HR_Mgt_API.ViewTemporaryIDsRequestBody();
            inValue.Body.status = status;
            inValue.Body.sessionId = sessionId;
            return ((WebApplication1.HR_Mgt_API.HRManagementAPISoap)(this)).ViewTemporaryIDsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.HR_Mgt_API.GetAPIStatsResponse WebApplication1.HR_Mgt_API.HRManagementAPISoap.GetAPIStats(WebApplication1.HR_Mgt_API.GetAPIStatsRequest request) {
            return base.Channel.GetAPIStats(request);
        }
        
        public string GetAPIStats() {
            WebApplication1.HR_Mgt_API.GetAPIStatsRequest inValue = new WebApplication1.HR_Mgt_API.GetAPIStatsRequest();
            inValue.Body = new WebApplication1.HR_Mgt_API.GetAPIStatsRequestBody();
            WebApplication1.HR_Mgt_API.GetAPIStatsResponse retVal = ((WebApplication1.HR_Mgt_API.HRManagementAPISoap)(this)).GetAPIStats(inValue);
            return retVal.Body.GetAPIStatsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.HR_Mgt_API.GetAPIStatsResponse> WebApplication1.HR_Mgt_API.HRManagementAPISoap.GetAPIStatsAsync(WebApplication1.HR_Mgt_API.GetAPIStatsRequest request) {
            return base.Channel.GetAPIStatsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.HR_Mgt_API.GetAPIStatsResponse> GetAPIStatsAsync() {
            WebApplication1.HR_Mgt_API.GetAPIStatsRequest inValue = new WebApplication1.HR_Mgt_API.GetAPIStatsRequest();
            inValue.Body = new WebApplication1.HR_Mgt_API.GetAPIStatsRequestBody();
            return ((WebApplication1.HR_Mgt_API.HRManagementAPISoap)(this)).GetAPIStatsAsync(inValue);
        }
    }
}
